//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brows.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public double zoomfactor {
            get {
                return ((double)(this["zoomfactor"]));
            }
            set {
                this["zoomfactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classical Radio")]
        public string appName {
            get {
                return ((string)(this["appName"]));
            }
            set {
                this["appName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>www.classicalwcrb.org/</string>
  <string>www.br.de/radio/live/br-klassik/</string>
  <string>www1.wdr.de/radio/wdr3/</string>
  <string>www.br-klassik.de/index.html</string>
  <string>www.mdr.de/klassik/index.html</string>
  <string>www.npoklassiek.nl/online-radio-luisteren/gedraaid</string>
  <string>www.vrt.be/vrtmax/livestream/audio/klaracontinuo/</string>
  <string>www.vrt.be/vrtmax/livestream/audio/klara/</string>
  <string>www.bbc.co.uk/sounds/play/live/bbc_radio_three</string>
  <string>www.concertzender.nl/themakanalen/</string>
  <string>google.com</string>
  <string>www.bbc.com/news/us-canada</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection favorites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["favorites"]));
            }
            set {
                this["favorites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int startUpIndex {
            get {
                return ((int)(this["startUpIndex"]));
            }
            set {
                this["startUpIndex"] = value;
            }
        }
    }
}
